import { Inter as FontSans } from "next/font/google";

import type { Metadata } from "next";

import "./globals.css";
import { AccountProvider } from "@/components/context/account";
import AuthProvider from "@/components/context/auth";
import { Footer } from "@/components/organisms/footer";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background flex h-screen flex-col font-sans antialiased ",
          fontSans.variable
        )}
      >
        <AuthProvider>
          <AccountProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
              <Footer />
            </ThemeProvider>
          </AccountProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
