import { Inter as FontSans } from "next/font/google";

import type { Metadata } from "next";

import "./globals.css";
import { AccountProvider } from "@/components/context/account";
import { Footer } from "@/components/organisms/footer";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex flex-col h-screen bg-background antialiased font-sans ",
          fontSans.variable
        )}
      >
        <AccountProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Footer />
          </ThemeProvider>
        </AccountProvider>
      </body>
    </html>
  );
}
